### ISSUE TITLE
yarn run build fails

### ISSUE THREAD

**Issue by padamshrestha** [OasisDigital/scalable-enterprise-angular#24]
Log:
======================
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @oasisdigital/employee-rest-server@1.0.0~prebuild: @oasisdigital/employee-rest-server@1.0.0
6 silly lifecycle @oasisdigital/employee-rest-server@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle @oasisdigital/employee-rest-server@1.0.0~build: @oasisdigital/employee-rest-server@1.0.0
8 verbose lifecycle @oasisdigital/employee-rest-server@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle @oasisdigital/employee-rest-server@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Projects\github\scalable-enterprise-angular\servers\employee-rest-server\node_modules\.bin;C:\Projects\github\scalable-enterprise-angular\node_modules\.bin;C:\Users\padam\AppData\Local\Yarn\config\link\node_modules\.bin;C:\Projects\github\scalable-enterprise-angular\node_modules\.bin;C:\Users\padam\AppData\Local\Yarn\config\link\node_modules\.bin;C:\Program Files (x86)\Yarn\bin\node-gyp-bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Python27;;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Ruby21-x64\bin;;C:\Program Files\Docker Toolbox;C:\Users\padam\AppData\Roaming\npm;C:\Users\padam\AppData\Local\Yarn\.bin
10 verbose lifecycle @oasisdigital/employee-rest-server@1.0.0~build: CWD: C:\Projects\github\scalable-enterprise-angular\servers\employee-rest-server
11 silly lifecycle @oasisdigital/employee-rest-server@1.0.0~build: Args: [ '/d /s /c', 'tsc --outDir build' ]
12 silly lifecycle @oasisdigital/employee-rest-server@1.0.0~build: Returned: code: 2  signal: null
13 info lifecycle @oasisdigital/employee-rest-server@1.0.0~build: Failed to exec build script
14 verbose stack Error: @oasisdigital/employee-rest-server@1.0.0 build: `tsc --outDir build`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @oasisdigital/employee-rest-server@1.0.0
16 verbose cwd C:\Projects\github\scalable-enterprise-angular\servers\employee-rest-server
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v7.8.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 2
23 error @oasisdigital/employee-rest-server@1.0.0 build: `tsc --outDir build`
23 error Exit status 2
24 error Failed at the @oasisdigital/employee-rest-server@1.0.0 build script 'tsc --outDir build'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the @oasisdigital/employee-rest-server package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     tsc --outDir build
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs @oasisdigital/employee-rest-server
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls @oasisdigital/employee-rest-server
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]
26 warn Local package.json exists, but node_modules missing, did you mean to install?

**Comment by padamshrestha** [comment]
works on dev branch. Thnx for the fix.
